---

- name: Install neovim python dependencies
  apt: name={{ item }} state=present
  with_items:
    - "{{ python_required_packages }}"
  become: true

- name: Install You Complete Me dependencies
  apt: name={{ item }} state=present
  with_items:
    - "{{ ycm_packages }}"
  become: true

- name: Install neovim
  apt: name=neovim state=present
  become: true

- name: Create nvim directory
  file:
    path: "{{ neovim_config_dir }}/bundle"
    state: directory

- name: Download init.vim
  get_url:
      url: "{{ vimrc_raw_gist_url }}"
      dest: "{{ neovim_config_dir }}/bundle/init.vim"

- name: Install vim plugins 
  command: nvim "+silent! PlugInstall!" +qall!

- name: Build YCM
  command: python3 "{{ user_dir }}/.vim/bundle/YouCompleteMe/install.py"

- name: Create backups folder
  file:
    path: "{{ user_dir }}/.vim/backups"
    state: directory
